version: "3"
volumes:
  odoo-data:
services:
  odoo:
    image: odoo:16
    ports:
      - 8069:8069
      - 8072:8072
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - ODOO_RC=/etc/odoo/odoo.conf
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
    volumes:
      - ./dump.sql:/dump.sql
      - ./dump.dump:/dump.dump
      
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - odoo