name: Infrastructure CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Checkov for infrastructure security checks
        uses: bridgecrewio/checkov-action@master

  code_quality:
    runs-on: ubuntu-latest
    needs: security_checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectKey: odoo-project
          token: ${{ secrets.SONAR_TOKEN }}

  build_and_test:
    runs-on: ubuntu-latest
    needs: code_quality

  deploy_to_staging:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Deploy to Staging
        run: |
          terraform apply --auto-approve --config ${{ secrets.PROD_CONFIG }}
      - name: Wait for manual approval
        uses: actions/manual-approval@latest
        with:
          ref: ${{ github.ref }}

  deploy_to_production:
    runs-on: ubuntu-latest
    needs: deploy_to_staging
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy to Production
        run: terraform apply --auto-approve --config ${{ secrets.PROD_CONFIG }}
